# .azure-pipelines/pr-validation.yml

# Trigger on Pull Requests targeting the 'main' branch
pr:
  branches:
    include:
    - main
  paths:
    include:
    - 'src/AdventureWorks_Azs.database/**'

jobs:
- job: RunForAllEnvironments
  displayName: 'Validate and Deploy PR to Non-Prod'
# Define the matrix strategy
  strategy:
    matrix:
      DEV:
        environmentName: 'DEV'
        serviceConnection: 'DEV Azure Connection' 
        variableGroup: 'DEV Secrets'        
      QA:
        environmentName: 'QA'
        serviceConnection: 'QA Azure Connection'  
        variableGroup: 'QA Secrets'         

  pool:
    vmImage: 'windows-latest'

  
  steps:
    - template: pr-deploy-steps.yml
      parameters:
        environmentName: $(environmentName)
        serviceConnection: $(serviceConnection)
        variableGroup: $(variableGroup)